name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * */3 * *' # Runs every hour, on the hour, every three days
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Fountainpencreator's posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: FPC
          feed_list: "https://www.fountainpencreator.com/index.xml#feed"
      - name: Pull in Gianlucafiore.it's posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: GF
          feed_list: "https://www.gianlucafiore.it/index.xml#feed"
